---
language: python
python: "3.9"

services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
script:
  - molecule test
env:
  jobs:
    - DOCKER_IMAGE_BASE=idealista/jdk:8u302-stretch-openjdk-headless
    - DOCKER_IMAGE_BASE=idealista/jdk:8u292-buster-adoptopenjdk-headless
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
