---
- name: SOLR_EXPORTER | Setting configuration up
  copy:
    src: "{{ prometheus_solr_exporter_config_file }}"
    dest: "{{ prometheus_solr_exporter_config_location }}"
    owner: "{{ prometheus_solr_exporter_user }}"
    group: "{{ prometheus_solr_exporter_group }}"
    mode: '0660'
  when: prometheus_solr_exporter_config_file
  notify: SOLR_EXPORTER | Restart service
