---
- name: SOLR_EXPORTER | Copying service definition
  template:
    src: prometheus_solr_exporter.service.j2
    dest: /etc/systemd/system/prometheus_solr_exporter.service
    owner: root
    group: root
    mode: 0644

- name: SOLR_EXPORTER | Enabling service daemon
  systemd:
    name: prometheus_solr_exporter
    state: started
    enabled: true
    daemon_reload: true
