---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: zookeeper
    hostname: zookeeper
    image: idealista/zookeeper:latest
    pre_build_image: true
    privileged: true
    config:
      limits.cpu: 2
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    exposed_ports:
      - 2181/tcp
    groups:
      - solr
      - zookeeper
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr

  - name: solrcloud1
    hostname: solrcloud1
    image: ${DOCKER_IMAGE_BASE:-idealista/jdk:8u265-stretch-openjdk-headless}
    privileged: false
    config:
      limits.cpu: 2
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    groups:
      - solr
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr
    exposed_ports:
      - 8983/tcp

  - name: solrcloud2
    hostname: solrcloud2
    image: ${DOCKER_IMAGE_BASE:-idealista/jdk:8u265-stretch-openjdk-headless}
    privileged: false
    config:
      limits.cpu: 2
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    groups:
      - solr
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr
    exposed_ports:
      - 8983/tcp

  - name: prometheus_solr_exporter
    hostname: prometheus_solr_exporter
    image: ${DOCKER_IMAGE_BASE:-idealista/jdk:8u265-stretch-openjdk-headless}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    groups:
      - solr
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr
    exposed_ports:
      - 9854/tcp

provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: facts

verifier:
  name: ansible
  directory: ./tests
