---
- name: Prepare Solr Cloud
  gather_facts: yes
  hosts: solrcloud
  pre_tasks:
    - name: Overriding vars
      include_vars:
        file: vars/solrcloud.yml
  roles:
    - role: solrcloud_role
